# Generated by Django 5.1.4 on 2025-01-09 15:46

import file.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='file',
            field=models.FileField(upload_to=file.models.generate_random_filename),
        ),
    ]
